name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          package-manager-cache: false
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          wranglerVersion: "4.80.0"
          accountId: 3f28d3a5c9a4bdc4a451bb2ce2ba89be
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
